config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :posts
  resources :comments
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, :header, :body , presence: true
  has_many :comments, dependent: :destroy
  mount_uploader :thumb, ThumbUploader
  self.per_page = 10
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstName, :lastName, presence: true
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def full_name
    "#{firstName.capitalize} #{lastName.upcase}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    authorized_attributes = params.require(:comment).permit(
        :body
    )
    @comment = Comment.new authorized_attributes
    @comment.user = current_user
    @comment.update_attributes params[:comment].permit(get_comment_params)

    if @comment.save
      redirect_to(post_path(@comment.post))
    else
      redirect_to(post_path(@comment.post))
    end
  end

  def get_comment_params
    return :body, :post_id
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user == current_user #check rigths of current user
      post = @comment.post
      @comment.destroy
      redirect_to post_path(post)
    else
      render 'post/error'
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  def index
    @posts = Post.all.paginate(:page => params[:page]).order(updated_at: :desc)
  end

  def load_post
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    authorized_attributes = params.require(:post).permit(
        :title,
        :header,
        :body,
        :thumb
    )
    @post = Post.new authorized_attributes
    @post.user = current_user

    if @post.save
      redirect_to(posts_path)
    else
      render 'new'
    end
  end

  def edit
    if @post.user == current_user #check rigths of current user
      render 'edit'
    else
      render 'posts/error'
    end
  end

  def update
    if @post.user == current_user #check rigths of current user
      authorized_attributes = params.require(:post).permit(
          :title,
          :header,
          :body,
          :thumb
      )
      if @post.update_attributes authorized_attributes
        redirect_to(post_path)
      else
        render 'edit'
      end
    else
      render 'post/error'
    end
  end

  def destroy
    if @post.user == current_user #check rigths of current user
      @post.destroy
      redirect_to posts_path
    else
      render 'post/error'
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:firstName, :lastName, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstName, :lastName, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<h2>Add new comment</h2>
<hr>
<%=  form_for @comment do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, :class => "form-control" %>
    <% if @comment.errors[:body].present? %>
      <div class="error">
        <%= @comment.errors[:body].to_sentence %>
      </div>
    <% end %>
  </div>
  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.submit :class => "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog NEDELEC</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div id="main">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container">
      <%= link_to("Guillaume's blog", root_path, :class => "navbar-brand") %>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to("Add post", new_post_path, :class => "nav-link") %>
          </li>
          <li class="nav-item">
            <%= link_to("View my profile", user_path(current_user), :class => "nav-link") %>
          </li>
          <li class="nav-item">
            <%= link_to(current_user.full_name + " - Logout", destroy_user_session_path, :class => "nav-link", method: :delete) %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to("Log In", new_user_session_path, :class => "nav-link")%>
          </li>
          <li class="nav-item">
            <%= link_to("Sign up", new_user_registration_path, :class => "nav-link") %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <main class="container">
    <% if notice.present? %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <%end%>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert"><%= alert %></div>
    <% end %>
    <%= yield %>
  </main>
  <footer>
    <div class="text-center"> Guillaume NEDELEC - LP DAWIN ALT</div>
  </footer>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="row justify-content-center" >
  <%=  form_for @post, :html => { :multipart => true }  do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control" %>
      <% if @post.errors[:title].present? %>
        <div class="error">
          <%= @post.errors[:title].to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :header %>
      <%= f.text_area :header, :class => "form-control" %>
      <% if @post.errors[:header].present? %>
        <div class="error">
          <%= @post.errors[:header].to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, :class => "form-control" %>
      <% if @post.errors[:body].present? %>
        <div class="error">
          <%= @post.errors[:body].to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :thumb %>
      <%= f.file_field :thumb, :class => "form-control"%>
      <% if @post.errors[:thumb].present? %>
        <div class="error">
          <%= @post.errors[:thumb].to_sentence %>
        </div>
      <% end %>
    </div>

    <% if @post.new_record? %>
      <%= f.submit :class => "btn btn-primary"%><%= link_to "Cancel", posts_path, :class => "btn btn-danger" %>
    <% else %>
      <%= f.submit :class => "btn btn-primary"%><%= link_to "Cancel", post_path(@post), :class => "btn btn-danger" %>
    <% end %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<hr>

<div class="form">
  <%= render "form" %>
</div>

app/views/posts/error.html.erb
<div class="alert alert-danger">
  You're not authorized to access this page.
</div>

app/views/posts/index.html.erb
<h1>Last posts</h1>
<hr>
<% if @posts.empty? %>
  <p><i>No posts...</i></p>
<% else %>
  <ul class="list-group end-page">
    <% @posts.each do |p| %>
      <li class="list-group-item">
        <div class="media">
          <% if p.thumb.url.nil? %>
            <%= image_tag("/no_image.svg", :class => "align-self-center mr-3 img-list") %>
          <% else %>
            <%= image_tag(p.thumb.url, :class => "align-self-center mr-3 img-list") %>
          <% end %>
          <div class="media-body media-center">
            <h3 class="mt-0"><%= p.title %></h3>
            <p class="mt-0"><i class="fa fa-user-o"></i><i> <%= link_to(p.user.full_name, user_path(p.user)) %></i></p>
            <p class="mt-0"><i class="fa fa-calendar-o"></i><i> <%= p.updated_at.localtime.strftime("%d/%m/%Y - %T") %></i></p>
            <p><%= p.header %>...</p>
            <%= link_to((fa_icon "eye", text: "View post"), post_path(p), :class => "btn btn-primary") %>
            <% if user_signed_in? and current_user == p.user %>
              <%= link_to((fa_icon "edit", text: "Edit post"), edit_post_path(p), :class => "btn btn-warning") %>
              <%= link_to((fa_icon "trash", text: "Remove post"), post_path(p), method: :delete, data: {confirm: "Are you sure ?"}, :class => "btn btn-danger" ) %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="end-page">
    <%= will_paginate @posts %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add new post</h1>
<hr>

<div class="form">
  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<h1 class="text-center"><%= @post.title %></h1>
<hr>
<p class="text-center">Author : <%= link_to(@post.user.full_name, user_path(@post.user)) %></p>
<p class="text-center">Last update : <%= @post.updated_at.localtime.strftime("%d/%m/%Y - %T") %></p>
<div class="text-center well">
  <% if @post.thumb.url.nil? %>
    <%= image_tag("/no_image.svg", :class => "img-full") %>
  <% else %>
    <%= image_tag(@post.thumb.url, :class => "img-full") %>
  <% end %>
</div>
<div class="section">
  <hr>
  <b>Chapeau : </b>
  <hr>
  <p><%= @post.header %></p>
</div>
<div class="section">
  <hr>
  <b>Content : </b>
  <hr>
  <p><%= @post.body %></p>
</div>
<hr>
<div class="text-center end-page">
  <% if user_signed_in? and current_user == @post.user %>
    <%= link_to((fa_icon "edit", text: "Edit post"), edit_post_path(@post), :class => "btn btn-warning") %>
    <%= link_to((fa_icon "trash", text: "Remove post"), post_path(@post), method: :delete, data: {confirm: "Are you sure ?"}, :class => "btn btn-danger" ) %>
  <% end %>
</div>

<h2>Comments</h2>
<hr>
<% if @post.comments.empty? %>
  <p class="end-page"><i>No comments...</i></p>
<% else %>
  <ul class="list-group end-page">
    <% @post.comments.each do |c| %>
      <li class="list-group-item">
        <div class="media">
          <div class="media-body media-center">
            <p class="mt-0"><i class="fa fa-user-o"></i><i> <%= c.user.full_name %></i></p>
            <p class="mt-0"><i class="fa fa-calendar-o"></i><i> <%= c.updated_at.localtime.strftime("%d/%m/%Y - %T") %></i></p>
            <p><%= c.body %></p>
            <% if user_signed_in? and current_user ==c.user %>
              <%= link_to((fa_icon "trash", text: "Remove comment"), comment_path(c), method: :delete, data: {confirm: "Are you sure ?"}, :class => "btn btn-danger") %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>
<% if user_signed_in? %>
  <div class="end-page">
    <%= render "comments/form", locals: {comment: @comment, post: @post} %>
  </div>
<% end %>

app/views/users/show.html.erb
<h2>User informations</h2>
<hr>
<div class="well">
  <p><b>Prénom : </b><%= @user.firstName%></p>
  <p><b>Nom : </b><%= @user.lastName%></p>
  <p><b>Email : </b><%= @user.email%></p>
</div>

<h2><%= @user.firstName.capitalize%>'s posts</h2>
<hr>
<% if @user.posts.empty? %>
  <p><i>No posts...</i></p>
<% else %>
  <ul class="list-group end-page">
    <% @user.posts.each do |p| %>
      <li class="list-group-item">
        <div class="media">
          <% if p.thumb.url.nil? %>
            <%= image_tag("/no_image.svg", :class => "align-self-center mr-3 img-list") %>
          <% else %>
            <%= image_tag(p.thumb.url, :class => "align-self-center mr-3 img-list") %>
          <% end %>
          <div class="media-body media-center">
            <h3 class="mt-0"><%= p.title %></h3>
            <p class="mt-0"><i class="fa fa-user-o"></i><i> <%= p.user.full_name %></i></p>
            <p class="mt-0"><i class="fa fa-calendar-o"></i><i> <%= p.updated_at.localtime.strftime("%d/%m/%Y - %T") %></i></p>
            <p><%= p.header %>...</p>
            <%= link_to((fa_icon "eye", text: "View post"), post_path(p), :class => "btn btn-primary") %>
            <%= link_to((fa_icon "edit", text: "Edit post"), edit_post_path(p), :class => "btn btn-warning") %>
            <%= link_to((fa_icon "trash", text: "Remove post"), post_path(p), method: :delete, data: {confirm: "Are you sure ?"}, :class => "btn btn-danger") %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>